checking if mandatroy environment variable is available or not

diff --git a/packages/backend/docker-compose.yml b/packages/backend/docker-compose.yml
--- a/packages/backend/docker-compose.yml
+++ b/packages/backend/docker-compose.yml
@@ -21,7 +21,14 @@ services:
     ports:
       - "9000:3000"
     working_dir: /usr/app/packages/backend
-    command: sh -c "pnpm run db:migrate && pnpm run db:seed:all && pnpm run dev"
+    command: >
+      sh -c '
+        if [ -z "$${OPENAI_API_KEY}" ]; then
+          echo "Error: OPENAI_API_KEY is not set"
+          exit 1
+        fi
+        pnpm run db:migrate && pnpm run db:seed:all && pnpm run dev
+      '
     depends_on:
       db:
         condition: service_healthy  
@@ -29,8 +36,8 @@ services:
     image: mysql:8.4
     container_name: khajanchi-db
     environment:
-      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
-      - MYSQL_DATABASE=${DB_DATABASE}
+      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-mydbpwd}
+      - MYSQL_DATABASE=${DB_DATABASE:-khajanchi}
     ports:
       - "3306:3306"
     volumes:
